import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

// Daftar 20 Sekolah SD (20 Regu Putra & 20 Regu Putri = 40 Regu)
const DEFAULT_PESERTA_SD = [
  // --- 20 REGU PUTRA SD (101 - 120) ---
  {
    nomor_dada: 101,
    nama_regu: "Regu Garuda",
    pangkalan: "SDN 1 Mekar Baru",
    no_gudep: "01.001 - 01.002",
    kontak_person: "083875644201",
    email: "sdn1mekarbaru@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 102,
    nama_regu: "Regu Elang",
    pangkalan: "SDN 2 Mekar Baru",
    no_gudep: "01.003 - 01.004",
    kontak_person: "083875644202",
    email: "sdn2mekarbaru@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 103,
    nama_regu: "Regu Rajawali",
    pangkalan: "SDN 3 Mekar Baru",
    no_gudep: "01.005 - 01.006",
    kontak_person: "083875644203",
    email: "sdn3mekarbaru@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 104,
    nama_regu: "Regu Singa",
    pangkalan: "SDN Klutuk 1",
    no_gudep: "01.007 - 01.008",
    kontak_person: "083875644204",
    email: "sdnklutuk1@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 105,
    nama_regu: "Regu Harimau",
    pangkalan: "SDN Klutuk 2",
    no_gudep: "01.009 - 01.010",
    kontak_person: "083875644205",
    email: "sdnklutuk2@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 106,
    nama_regu: "Regu Badak",
    pangkalan: "SDN Kosambi Dalam 1",
    no_gudep: "01.011 - 01.012",
    kontak_person: "083875644206",
    email: "sdnkosambidalam1@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 107,
    nama_regu: "Regu Banteng",
    pangkalan: "SDN Kosambi Dalam 2",
    no_gudep: "01.013 - 01.014",
    kontak_person: "083875644207",
    email: "sdnkosambidalam2@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 108,
    nama_regu: "Regu Serigala",
    pangkalan: "SDN Jenggot 1",
    no_gudep: "01.015 - 01.016",
    kontak_person: "083875644208",
    email: "sdnjenggot1@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 109,
    nama_regu: "Regu Kancil",
    pangkalan: "SDN Jenggot 2",
    no_gudep: "01.017 - 01.018",
    kontak_person: "083875644209",
    email: "sdnjenggot2@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 110,
    nama_regu: "Regu Kuda",
    pangkalan: "SDN Cijeruk 1",
    no_gudep: "01.019 - 01.020",
    kontak_person: "083875644210",
    email: "sdncijeruk1@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 111,
    nama_regu: "Regu Lumba-lumba",
    pangkalan: "SDN Cijeruk 2",
    no_gudep: "01.021 - 01.022",
    kontak_person: "083875644211",
    email: "sdncijeruk2@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 112,
    nama_regu: "Regu Hiu",
    pangkalan: "SDN Gandaria 1",
    no_gudep: "01.023 - 01.024",
    kontak_person: "083875644212",
    email: "sdngandaria1@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 113,
    nama_regu: "Regu Beruang",
    pangkalan: "SDN Gandaria 2",
    no_gudep: "01.025 - 01.026",
    kontak_person: "083875644213",
    email: "sdngandaria2@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 114,
    nama_regu: "Regu Gajah",
    pangkalan: "SDN Waliwis",
    no_gudep: "01.027 - 01.028",
    kontak_person: "083875644214",
    email: "sdnwaliwis@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 115,
    nama_regu: "Regu Cendrawasih",
    pangkalan: "SDN Kedaung",
    no_gudep: "01.029 - 01.030",
    kontak_person: "083875644215",
    email: "sdnkedaung@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 116,
    nama_regu: "Regu Merak",
    pangkalan: "MI Nurul Huda Mekar Baru",
    no_gudep: "01.031 - 01.032",
    kontak_person: "083875644216",
    email: "minurulhuda@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 117,
    nama_regu: "Regu Macan",
    pangkalan: "MI Al-Falah Mekar Baru",
    no_gudep: "01.033 - 01.034",
    kontak_person: "083875644217",
    email: "mialfalah@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 118,
    nama_regu: "Regu Anoa",
    pangkalan: "MI Mathlaul Anwar",
    no_gudep: "01.035 - 01.036",
    kontak_person: "083875644218",
    email: "mimathlaulanwar@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 119,
    nama_regu: "Regu Komodo",
    pangkalan: "MI Al-Khairiyah",
    no_gudep: "01.037 - 01.038",
    kontak_person: "083875644219",
    email: "mialkhairiyah@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 120,
    nama_regu: "Regu Jalak",
    pangkalan: "MI Darul Ulum Mekar Baru",
    no_gudep: "01.039 - 01.040",
    kontak_person: "083875644220",
    email: "midarululum@gmail.com",
    kategori: "SD",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },

  // --- 20 REGU PUTRI SD (121 - 140) ---
  {
    nomor_dada: 121,
    nama_regu: "Regu Melati",
    pangkalan: "SDN 1 Mekar Baru",
    no_gudep: "01.001 - 01.002",
    kontak_person: "083875644221",
    email: "sdn1mekarbaru@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 122,
    nama_regu: "Regu Mawar",
    pangkalan: "SDN 2 Mekar Baru",
    no_gudep: "01.003 - 01.004",
    kontak_person: "083875644222",
    email: "sdn2mekarbaru@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 123,
    nama_regu: "Regu Anggrek",
    pangkalan: "SDN 3 Mekar Baru",
    no_gudep: "01.005 - 01.006",
    kontak_person: "083875644223",
    email: "sdn3mekarbaru@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 124,
    nama_regu: "Regu Dahlia",
    pangkalan: "SDN Klutuk 1",
    no_gudep: "01.007 - 01.008",
    kontak_person: "083875644224",
    email: "sdnklutuk1@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 125,
    nama_regu: "Regu Sakura",
    pangkalan: "SDN Klutuk 2",
    no_gudep: "01.009 - 01.010",
    kontak_person: "083875644225",
    email: "sdnklutuk2@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 126,
    nama_regu: "Regu Teratai",
    pangkalan: "SDN Kosambi Dalam 1",
    no_gudep: "01.011 - 01.012",
    kontak_person: "083875644226",
    email: "sdnkosambidalam1@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 127,
    nama_regu: "Regu Cempaka",
    pangkalan: "SDN Kosambi Dalam 2",
    no_gudep: "01.013 - 01.014",
    kontak_person: "083875644227",
    email: "sdnkosambidalam2@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 128,
    nama_regu: "Regu Kenanga",
    pangkalan: "SDN Jenggot 1",
    no_gudep: "01.015 - 01.016",
    kontak_person: "083875644228",
    email: "sdnjenggot1@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 129,
    nama_regu: "Regu Tulip",
    pangkalan: "SDN Jenggot 2",
    no_gudep: "01.017 - 01.018",
    kontak_person: "083875644229",
    email: "sdnjenggot2@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 130,
    nama_regu: "Regu Lavender",
    pangkalan: "SDN Cijeruk 1",
    no_gudep: "01.019 - 01.020",
    kontak_person: "083875644230",
    email: "sdncijeruk1@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 131,
    nama_regu: "Regu Edelweis",
    pangkalan: "SDN Cijeruk 2",
    no_gudep: "01.021 - 01.022",
    kontak_person: "083875644231",
    email: "sdncijeruk2@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 132,
    nama_regu: "Regu Lily",
    pangkalan: "SDN Gandaria 1",
    no_gudep: "01.023 - 01.024",
    kontak_person: "083875644232",
    email: "sdngandaria1@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 133,
    nama_regu: "Regu Asoka",
    pangkalan: "SDN Gandaria 2",
    no_gudep: "01.025 - 01.026",
    kontak_person: "083875644233",
    email: "sdngandaria2@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 134,
    nama_regu: "Regu Flamboyan",
    pangkalan: "SDN Waliwis",
    no_gudep: "01.027 - 01.028",
    kontak_person: "083875644234",
    email: "sdnwaliwis@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 135,
    nama_regu: "Regu Bougenville",
    pangkalan: "SDN Kedaung",
    no_gudep: "01.029 - 01.030",
    kontak_person: "083875644235",
    email: "sdnkedaung@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 136,
    nama_regu: "Regu Kamboja",
    pangkalan: "MI Nurul Huda Mekar Baru",
    no_gudep: "01.031 - 01.032",
    kontak_person: "083875644236",
    email: "minurulhuda@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 137,
    nama_regu: "Regu Matahari",
    pangkalan: "MI Al-Falah Mekar Baru",
    no_gudep: "01.033 - 01.034",
    kontak_person: "083875644237",
    email: "mialfalah@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 138,
    nama_regu: "Regu Krisan",
    pangkalan: "MI Mathlaul Anwar",
    no_gudep: "01.035 - 01.036",
    kontak_person: "083875644238",
    email: "mimathlaulanwar@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 139,
    nama_regu: "Regu Nusa Indah",
    pangkalan: "MI Al-Khairiyah",
    no_gudep: "01.037 - 01.038",
    kontak_person: "083875644239",
    email: "mialkhairiyah@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 140,
    nama_regu: "Regu Sedap Malam",
    pangkalan: "MI Darul Ulum Mekar Baru",
    no_gudep: "01.039 - 01.040",
    kontak_person: "083875644240",
    email: "midarululum@gmail.com",
    kategori: "SD",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
];

// Daftar 5 Sekolah SMP/MTs (5 Regu Putra & 5 Regu Putri = 10 Regu)
const DEFAULT_PESERTA_SMP = [
  // --- 5 REGU PUTRA SMP/MTS (201 - 205) ---
  {
    nomor_dada: 201,
    nama_regu: "Regu Cobra",
    pangkalan: "SMPN 1 Mekar Baru",
    no_gudep: "01.051 - 01.052",
    kontak_person: "083875644241",
    email: "smpn1mekarbaru@gmail.com",
    kategori: "SMP",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 202,
    nama_regu: "Regu Jaguar",
    pangkalan: "SMPN 2 Mekar Baru",
    no_gudep: "01.053 - 01.054",
    kontak_person: "083875644242",
    email: "smpn2mekarbaru@gmail.com",
    kategori: "SMP",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 203,
    nama_regu: "Regu Cheetah",
    pangkalan: "SMPN 3 Mekar Baru",
    no_gudep: "01.055 - 01.056",
    kontak_person: "083875644243",
    email: "smpn3mekarbaru@gmail.com",
    kategori: "SMP",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 204,
    nama_regu: "Regu Scorpio",
    pangkalan: "MTs Al-Falah Mekar Baru",
    no_gudep: "01.057 - 01.058",
    kontak_person: "083875644244",
    email: "mtsalfalah@gmail.com",
    kategori: "SMP",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 205,
    nama_regu: "Regu Puma",
    pangkalan: "MTs Nurul Huda Mekar Baru",
    no_gudep: "01.059 - 01.060",
    kontak_person: "083875644245",
    email: "mtsnurulhuda@gmail.com",
    kategori: "SMP",
    gender: "Laki-laki",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },

  // --- 5 REGU PUTRI SMP/MTS (206 - 210) ---
  {
    nomor_dada: 206,
    nama_regu: "Regu Aster",
    pangkalan: "SMPN 1 Mekar Baru",
    no_gudep: "01.051 - 01.052",
    kontak_person: "083875644246",
    email: "smpn1mekarbaru@gmail.com",
    kategori: "SMP",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 207,
    nama_regu: "Regu Anyelir",
    pangkalan: "SMPN 2 Mekar Baru",
    no_gudep: "01.053 - 01.054",
    kontak_person: "083875644247",
    email: "smpn2mekarbaru@gmail.com",
    kategori: "SMP",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 208,
    nama_regu: "Regu Magnolia",
    pangkalan: "SMPN 3 Mekar Baru",
    no_gudep: "01.055 - 01.056",
    kontak_person: "083875644248",
    email: "smpn3mekarbaru@gmail.com",
    kategori: "SMP",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 209,
    nama_regu: "Regu Raflesia",
    pangkalan: "MTs Al-Falah Mekar Baru",
    no_gudep: "01.057 - 01.058",
    kontak_person: "083875644249",
    email: "mtsalfalah@gmail.com",
    kategori: "SMP",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
  {
    nomor_dada: 210,
    nama_regu: "Regu Sepatu",
    pangkalan: "MTs Nurul Huda Mekar Baru",
    no_gudep: "01.059 - 01.060",
    kontak_person: "083875644250",
    email: "mtsnurulhuda@gmail.com",
    kategori: "SMP",
    gender: "Perempuan",
    is_verified: true,
    status_berkas: { ketersediaan: true, pendaftaran: true, biodata_peserta: true, biodata_pembina: true, bukti_pembayaran: true },
    catatan_berkas: "Berkas lengkap dan terverifikasi",
    total_nilai: 0,
  },
];

export async function POST(request) {
  try {
    const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
    const supabaseServiceKey =
      process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

    if (!supabaseUrl || !supabaseServiceKey) {
      return NextResponse.json({ error: "Konfigurasi Supabase Server belum lengkap." }, { status: 500 });
    }

    const supabaseAdmin = createClient(supabaseUrl, supabaseServiceKey, {
      auth: { persistSession: false },
    });

    const body = await request.json().catch(() => ({}));
    const targetKategori = body.kategori || "ALL"; // "SD", "SMP", or "ALL"

    let dataToInsert = [];
    if (targetKategori === "SD") dataToInsert = DEFAULT_PESERTA_SD;
    else if (targetKategori === "SMP") dataToInsert = DEFAULT_PESERTA_SMP;
    else dataToInsert = [...DEFAULT_PESERTA_SD, ...DEFAULT_PESERTA_SMP];

    // Cek apakah data sudah ada berdasarkan nomor dada
    const { data: existingPeserta } = await supabaseAdmin
      .from("peserta")
      .select("nomor_dada");

    const existingNomorDada = new Set((existingPeserta || []).map((p) => p.nomor_dada));
    const newPeserta = dataToInsert.filter((p) => !existingNomorDada.has(p.nomor_dada));

    if (newPeserta.length === 0) {
      return NextResponse.json({
        success: true,
        message: "Seluruh data sekolah/regu standar (50 regu aktif) sudah ada di sistem.",
        insertedCount: 0,
      });
    }

    const { data: inserted, error } = await supabaseAdmin
      .from("peserta")
      .insert(newPeserta)
      .select();

    if (error) {
      return NextResponse.json({ error: error.message }, { status: 500 });
    }

    return NextResponse.json({
      success: true,
      message: `Berhasil menambahkan ${inserted?.length || 0} regu resmi (Langsung Aktif & Terverifikasi)!`,
      insertedCount: inserted?.length || 0,
    });
  } catch (err) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
